
SELECT * FROM EMPLOYEES
SELECT * FROM EMPLOYEES_SALARIES

--CASE STATEMENTS -> IF CASE IS TRUE THEN  {} ELSE {}


--1, AGE
SELECT EMP_ID,EMP_NAME, AGE,
CASE
	WHEN AGE = 30 THEN 'LITTLE OLD'
	WHEN AGE > 25 THEN CONCAT(age , ' YOUNG')
	WHEN AGE < 22 THEN 'TEENAGER'
	ELSE 'OLD'
END AS OP
FROM EMPLOYEES


--[2] Salary hike for salesman 10%, accountant 5%, HR 0.5%, other 4%
SELECT E.EMP_ID,EMP_NAME,emp_role,salary,
CASE 
	WHEN EMP_ROLE = 'Salesman' THEN Salary + (Salary * .10)
	WHEN EMP_ROLE = 'Accountant' THEN Salary + (Salary * 0.05)
	ELSE (SALARY * 0.4)
END as salary_after_hike
FROM EMPLOYEES E
JOIN EMPLOYEES_SALARIES ON  E.EMP_ID = EMPLOYEES_SALARIES.EMP_ID


